CREATE VIEW EVNT_LST AS
(
SELECT
    EVNT_NUM
    ,EVNT_CD
    ,EVNT_NAME
    ,GROUP_CONCAT(EVNT_USR_NUM) EVNT_USR_NUM
    -- 場所コードは結合して場所を取ってくる。ストアドで
    ,PLC_CD
    ,STRT_YR AS YR
    ,STRT_MNTH AS MNTH
    ,STRT_DAY AS DAY
    ,STRT_HR AS HR
    ,STRT_MNT AS MNT
    ,STRT_SCND AS SCND
    ,"1" AS SE_CD
FROM
    T_EVNT_MSTR
WHERE
    CNCLMNT_CD <> 0
GROUP BY
    EVNT_NUM
    ,EVNT_NO
    ,EVNT_NAME

UNION ALL

SELECT DISTINCT
    EVNT_NUM
    ,EVNT_CD
    ,EVNT_NAME
    ,GROUP_CONCAT(EVNT_USR_NUM) AS EVNT_USR_NUM
    ,PLC_CD
    ,END_YR AS YR
    ,END_MNTH AS MNTH
    ,END_DAY AS DAY
    ,END_HR AS HR
    ,END_MNT AS MNT
    ,END_SCND AS SCND
    ,"2" AS SE_CD
FROM
    T_EVNT_MSTR
WHERE
    CNCLMNT_CD <> 0
GROUP BY
    EVNT_NUM
    ,EVNT_NO
    ,EVNT_NAME
)
ORDER BY
    YR
    ,MNTH
    ,DAY
    ,HR
    ,MNT
    ,SCND
    ASC